apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-machine-learning
spec:
  selector:
    matchLabels:
      preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
      preview.immich.app/component: machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
        preview.immich.app/component: machine-learning
    spec:
      containers:
        - args:
            - ./entrypoint.sh
          command:
            - /bin/sh
          envFrom:
            - configMapRef:
                name: {{include "immich-preview.fullnamePrefix" .}}-config
          image: ghcr.io/immich-app/immich-machine-learning:{{ .Values.tag }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3003
            timeoutSeconds: 1
          name: server
          ports:
            - containerPort: 3003
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3003
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 3003
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: library
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: {{include "immich-preview.fullnamePrefix" .}}-library