---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      externalResizer:
        enabled: false

    csiDriver:
      name: "org.democratic-csi.zfs-local-dataset"
      storageCapacity: false
      fsGroupPolicy: File

    driver:
      config:
        driver: zfs-local-dataset

        zfs:
          datasetParentName: storage/k8s/volumes
          detachedSnapshotsDatasetParentName: storage/k8s/snapshots

          datasetEnableQuotas: true
          datasetEnableReservation: false

    storageClasses:
      - name: zfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false
        parameters:
          fsType: zfs

    volumeSnapshotClasses:
      - name: zfs
        deletionPolicy: Retain