{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
      preview.immich.app/component: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
        preview.immich.app/component: server
        podbump.bo0tzz.me/enabled: "true"
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:{{ .Values.tag }}
          imagePullPolicy: Always
          args:
            - ./start-server.sh
          command:
            - /bin/sh
          envFrom:
            - configMapRef:
                name: {{include "immich-preview.fullnamePrefix" .}}-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: immich-previews-database-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: immich-previews-database-secret
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3001
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3001
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 3001
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: library
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: {{include "immich-preview.fullnamePrefix" .}}-library
{{- end}}