---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./auth/oauth2-proxy.yaml
  # Just for testing
  - ./podinfo/deployment.yaml
  - ./podinfo/service.yaml
  - ./podinfo/ingress.yaml