---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./auth/oauth2-proxy.yaml
  - ./preview-controller/deployment.yaml
  - ./preview-controller/service.yaml
  - ./preview-controller/rbac.yaml
  - ./dashboard/helmrelease.yaml