---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-cloud-to-app-redirect
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
  path: ./kubernetes/apps/networking/ingress-nginx/redirect
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
