apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-config
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: {{include "immich-preview.fullnamePrefix" .}}-database-rw
  NODE_ENV: production
  REDIS_HOSTNAME: {{include "immich-preview.fullnamePrefix" .}}-redis
  IMMICH_MACHINE_LEARNING_URL: http://{{include "immich-preview.fullnamePrefix" .}}-machine-learning:3003
