apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-database
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14.11-v0.2.0
  primaryUpdateStrategy: unsupervised

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  
  storage:
    size: 1Gi
    storageClass: local-path
  minSyncReplicas: 0

  bootstrap:
    recovery:
      backup:
        name: immich-preview-source
      recoveryTarget:
        backupID: "20240306T124651"
        targetImmediate: true
