apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-database
spec:
  instances: {{include "immich-preview.replicas" .}}
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: local-path
  minSyncReplicas: 0

  bootstrap:
    initdb:
      database: immich
  # TODO:
  # bootstrap:
  #   recovery:
  #     backup:
  #       name: backup-example