kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-library
spec:
  storageClassName: zfs
  dataSource:
    name: immich-preview-library
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi