---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database-minio
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minio
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
