apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-redis
spec:
  selector:
    matchLabels:
      preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
      preview.immich.app/component: redis
  replicas: 1
  template:
    metadata:
      labels:
        preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
        preview.immich.app/component: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
           - containerPort: 6379