apiVersion: v1
kind: Service
metadata:
  name: {{include "immich-preview.fullnamePrefix" .}}-proxy
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    preview.immich.app/instance: {{include "immich-preview.fullnamePrefix" .}}
    preview.immich.app/component: proxy