apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-demo
  namespace: immich
  labels:
    preview.immich.app/managed: "true"
spec:
  interval: 15m
  chart:
    spec:
      chart: helm/immich-preview
      version: '0.1.2'
      sourceRef:
        kind: GitRepository
        name: immich-preview-charts
        namespace: flux-system
      interval: 1m
  values:
    tag: release
    url: demo.immich.cloud
    fullnamePrefixOverride: immich-demo
    loginPageMessage: |-
      This is a preview of the Immich release branch.<br>
      Email: <i>demo@immich.app</i><br>Password: <i>demo</i>