---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storage-democratic-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: storage-snapshot-controller
  path: ./kubernetes/apps/storage/democratic-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: democratic-csi
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
