apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-controller
  namespace: immich
  labels:
    app: preview-controller
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: preview-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: preview-controller
    spec:
      serviceAccountName: preview-controller
      containers:
        - name: preview-controller
          image: ghcr.io/bo0tzz/immich-preview-controller:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            # It's behind auth, this is fine for now, right? .-.
            - name: SECRET_KEY_BASE
              value: mOuC067fH6yfpK9ZJxJQpB0CeQHY8Gctj0bXAE0NzJWFR0GUS6e8k7bjbJdQuN9ccmGPiazyvKCcFUR9rnxKn7rVqSSW
          resources:
            requests:
              cpu: 20m
              memory: 200M
