apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-controller
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preview-controller
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: preview-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: preview-controller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: preview-controller
  namespace: immich