apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-controller
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: preview-controller
  namespace: immich
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: preview-controller-binding
  namespace: immich
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: preview-controller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: preview-controller