apiVersion: v1
kind: Service
metadata:
  labels:
    service: preview-controller
  name: preview-controller
  namespace: immich
spec:
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
  selector:
    app: preview-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: preview-controller
  namespace: immich
spec:
  ingressClassName: nginx
  rules:
  - host: preview.immich.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: preview-controller
            port:
              number: 8000
  tls:
  - hosts:
    - preview.immich.app
    secretName: preview-tls-web