apiVersion: v1
kind: Secret
metadata:
  name: immich-previews-database-secret
  namespace: previews
type: kubernetes.io/basic-auth
# I know, plain secrets. This isn't that important though
data:
  password: >-
    YXBkR2dCbm40S2w5RGY5dGN1NjdJNzRqbUd0YUpIZzIzUGxLemhDaXlsVnR4RlNpU3RKZ2p6dENFTk9aaDBlVQ==
  pgpass: >-
    aW1taWNoLXByZXZpZXctc291cmNlLWRhdGFiYXNlLXJ3OjU0MzI6aW1taWNoOmltbWljaDphcGRHZ0JubjRLbDlEZjl0Y3U2N0k3NGptR3RhSkhnMjNQbEt6aENpeWxWdHhGU2lTdEpnanp0Q0VOT1poMGVVCg==
  username: aW1taWNo
